title: jadru blog
author: jadru
url: https://jadru.github.io
description: > # description of the site (multiple lines allowed)
  Hope to make world better

permalink: /:slug.html

favicon: "./logo.png" # relative path to site's favicon

#theme: moonwalk # if you are using GitHub Pages, change it to remote_theme: abhinavs/moonwalk
remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "홈.." # customize text for homepage link in post layout
  date_format: "%Y년 %m월 %d일" # customize how date is formatted
  show_description: true # show blog description
  show_navbar: true # show horizontal navbar
  show_footer: true # show footer links in home page,add in _data/home.yml
  # following keys are using to create home layout
  show_projects: true # show projects as cards, add in _data/home.yml
  show_blog: true # show blog posts added in _posts
  show_old_projects: true # show old projects as cards, add in _data/home.yml
  show_misc_list: false # show generic vertical list for misc details, add _data/home.yml

soopr:
  publish_token: "" # sign up at https://www.soopr.co to get your publish token and personalize share and reaction options

highlighter: rouge

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
